image: golang:latest

stages:
  - build

building:
  stage: build
  script:
    - go get -u github.com/pepa65/becrypt
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w"
    - CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -ldflags="-s -w" -o becrypt_pi
    - CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -ldflags="-s -w" -o becrypt_bsd
    - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o becrypt_osx
    - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o becrypt.exe
  artifacts:
    name: becrypt
    paths:
     - becrypt
     - becrypt_pi
     - becrypt_bsd
     - becrypt_osx
     - becrypt.exe
