builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - freebsd
      - openbsd
      - plan9
      - linux
    goarch:
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
