upx:
  - enabled: true
    lzma: true
    compress: best
    goos: [linux]

archives:
- format: binary

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
      - dragonfly
      - plan9
      - linux
    goarch:
      - arm
      - arm64
      - amd64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

