name: becrypt
base: core20
version: 'v1.2.1'
summary: becrypt - CLI tool for generating and matching bcrypt hashes
description: |
 becryptl is a CLI tool for generating and matching bcrypt hashes of a specified cost

grade: stable
confinement: strict
architectures:
  - build-on: amd64

apps:
  becrypt:
    command: bin/becrypt

parts:
  becrypt:
    plugin: go
    go-channel: 1.19/stable
    source: https://github.com/pepa65/becrypt
    source-type: git
    source-tag: v1.2.1
    build-packages:
      - git
